version: '3.1'

services:
    php:
        image: php-cus
        restart: always
        ports:
            - 9090:80
        volumes:
            - ./src:/var/www/html/
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    mysql: